[
    {
        "userName": "johndoe",
        "email": "johndoe.user@example.com",
        "firstName": "John",
        "lastName": "Doe",
        "joinDate": "2024-11-07T00:00:00.000+00:00",
        "role": "CUSTOMER",
        "flagged": false,
    },
    {
        "userName": "sarasmith",
        "email": "sarasmith.user@example.com",
        "firstName": "Sara",
        "lastName": "Smith",
        "joinDate": "2024-11-07T00:00:00.000+00:00",
        "role": "INSTRUCTOR",
        "flagged": true,
    },
    {
        "userName": "brianlee",
        "email": "brianlee.user@example.com",
        "firstName": "Brian",
        "lastName": "Lee",
        "joinDate": "2024-11-07T00:00:00.000+00:00",
        "role": "INSTRUCTOR",
        "flagged": false,
    },
    {
        "userName": "emilyclarkUPDATED",
        "email": "emilyclark.user@example.com",
        "firstName": "Emily",
        "lastName": "Clark",
        "joinDate": "2024-11-07T00:00:00.000+00:00",
        "role": "INSTRUCTOR",
        "flagged": true,
    },
    {
        "userName": "davidmiller",
        "email": "davidmiller.user@example.com",
        "firstName": "David",
        "lastName": "Miller",
        "joinDate": "2024-11-07T00:00:00.000+00:00",
        "role": "ADMIN",
        "flagged": false,
    }
]
